### ISSUE TITLE
timeago.js issues + variables

### ISSUE THREAD

**Issue by Regis-Loyaute** [shaheen7a/MERN-Youtube-Clone#2]
Hello i'm experiencing issues with timeago.js. and also 3 variables at the end of the error message when trying to turn the project, i've already tried to reinstall timeago.js, to upgrade it without any luck.

Failed to parse source map from 'C:\Users\Administrator\Downloads\MERN-Youtube-Clone-main\MERN-Youtube-Clone-main\client\node_modules\timeago.js\src\format.ts' file: Error: ENOENT: no such file or directory, open 'C:\Users\Administrator\Downloads\MERN-Youtube-Clone-main\MERN-Youtube-Clone-main\client\node_modules\timeago.js\src\format.ts'

Failed to parse source map from 'C:\Users\Administrator\Downloads\MERN-Youtube-Clone-main\MERN-Youtube-Clone-main\client\node_modules\timeago.js\src\index.ts' file: Error: ENOENT: no such file or directory, open 'C:\Users\Administrator\Downloads\MERN-Youtube-Clone-main\MERN-Youtube-Clone-main\client\node_modules\timeago.js\src\index.ts'

Failed to parse source map from 'C:\Users\Administrator\Downloads\MERN-Youtube-Clone-main\MERN-Youtube-Clone-main\client\node_modules\timeago.js\src\lang\en_US.ts' file: Error: ENOENT: no such file or directory, open 'C:\Users\Administrator\Downloads\MERN-Youtube-Clone-main\MERN-Youtube-Clone-main\client\node_modules\timeago.js\src\lang\en_US.ts'

Failed to parse source map from 'C:\Users\Administrator\Downloads\MERN-Youtube-Clone-main\MERN-Youtube-Clone-main\client\node_modules\timeago.js\src\lang\zh_CN.ts' file: Error: ENOENT: no such file or directory, open 'C:\Users\Administrator\Downloads\MERN-Youtube-Clone-main\MERN-Youtube-Clone-main\client\node_modules\timeago.js\src\lang\zh_CN.ts'

Failed to parse source map from 'C:\Users\Administrator\Downloads\MERN-Youtube-Clone-main\MERN-Youtube-Clone-main\client\node_modules\timeago.js\src\realtime.ts' file: Error: ENOENT: no such file or directory, open 'C:\Users\Administrator\Downloads\MERN-Youtube-Clone-main\MERN-Youtube-Clone-main\client\node_modules\timeago.js\src\realtime.ts'

Failed to parse source map from 'C:\Users\Administrator\Downloads\MERN-Youtube-Clone-main\MERN-Youtube-Clone-main\client\node_modules\timeago.js\src\register.ts' file: Error: ENOENT: no such file or directory, open 'C:\Users\Administrator\Downloads\MERN-Youtube-Clone-main\MERN-Youtube-Clone-main\client\node_modules\timeago.js\src\register.ts'

Failed to parse source map from 'C:\Users\Administrator\Downloads\MERN-Youtube-Clone-main\MERN-Youtube-Clone-main\client\node_modules\timeago.js\src\utils\date.ts' file: Error: ENOENT: no such file or directory, open 'C:\Users\Administrator\Downloads\MERN-Youtube-Clone-main\MERN-Youtube-Clone-main\client\node_modules\timeago.js\src\utils\date.ts'

Failed to parse source map from 'C:\Users\Administrator\Downloads\MERN-Youtube-Clone-main\MERN-Youtube-Clone-main\client\node_modules\timeago.js\src\utils\dom.ts' file: Error: ENOENT: no such file or directory, open 'C:\Users\Administrator\Downloads\MERN-Youtube-Clone-main\MERN-Youtube-Clone-main\client\node_modules\timeago.js\src\utils\dom.ts'

src\pages\SignIn.jsx
  Line 74:10:  'email' is assigned a value but never used  no-unused-vars

src\pages\Video.jsx
  Line 10:8:  'Card' is defined but never used  no-unused-vars

src\redux\store.js
  Line 15:10:  'PersistGate' is defined but never used  no-unused-vars

Search for the keywords to learn more about each warning.
To ignore, add // eslint-disable-next-line to the line before.

WARNING in ./node_modules/timeago.js/esm/format.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from 'C:\Users\Administrator\Downloads\MERN-Youtube-Clone-main\MERN-Youtube-Clone-main\client\node_modules\timeago.js\src\format.ts' file: Error: ENOENT: no such file or directory, open 'C:\Users\Administrator\Downloads\MERN-Youtube-Clone-main\MERN-Youtube-Clone-main\client\node_modules\timeago.js\src\format.ts'

WARNING in ./node_modules/timeago.js/esm/index.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from 'C:\Users\Administrator\Downloads\MERN-Youtube-Clone-main\MERN-Youtube-Clone-main\client\node_modules\timeago.js\src\index.ts' file: Error: ENOENT: no such file or directory, open 'C:\Users\Administrator\Downloads\MERN-Youtube-Clone-main\MERN-Youtube-Clone-main\client\node_modules\timeago.js\src\index.ts'

WARNING in ./node_modules/timeago.js/esm/lang/en_US.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from 'C:\Users\Administrator\Downloads\MERN-Youtube-Clone-main\MERN-Youtube-Clone-main\client\node_modules\timeago.js\src\lang\en_US.ts' file: Error: ENOENT: no such file or directory, open 'C:\Users\Administrator\Downloads\MERN-Youtube-Clone-main\MERN-Youtube-Clone-main\client\node_modules\timeago.js\src\lang\en_US.ts'

WARNING in ./node_modules/timeago.js/esm/lang/zh_CN.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from 'C:\Users\Administrator\Downloads\MERN-Youtube-Clone-main\MERN-Youtube-Clone-main\client\node_modules\timeago.js\src\lang\zh_CN.ts' file: Error: ENOENT: no such file or directory, open 'C:\Users\Administrator\Downloads\MERN-Youtube-Clone-main\MERN-Youtube-Clone-main\client\node_modules\timeago.js\src\lang\zh_CN.ts'

WARNING in ./node_modules/timeago.js/esm/realtime.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from 'C:\Users\Administrator\Downloads\MERN-Youtube-Clone-main\MERN-Youtube-Clone-main\client\node_modules\timeago.js\src\realtime.ts' file: Error: ENOENT: no such file or directory, open 'C:\Users\Administrator\Downloads\MERN-Youtube-Clone-main\MERN-Youtube-Clone-main\client\node_modules\timeago.js\src\realtime.ts'

WARNING in ./node_modules/timeago.js/esm/register.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from 'C:\Users\Administrator\Downloads\MERN-Youtube-Clone-main\MERN-Youtube-Clone-main\client\node_modules\timeago.js\src\register.ts' file: Error: ENOENT: no such file or directory, open 'C:\Users\Administrator\Downloads\MERN-Youtube-Clone-main\MERN-Youtube-Clone-main\client\node_modules\timeago.js\src\register.ts'

WARNING in ./node_modules/timeago.js/esm/utils/date.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from 'C:\Users\Administrator\Downloads\MERN-Youtube-Clone-main\MERN-Youtube-Clone-main\client\node_modules\timeago.js\src\utils\date.ts' file: Error: ENOENT: no such file or directory, open 'C:\Users\Administrator\Downloads\MERN-Youtube-Clone-main\MERN-Youtube-Clone-main\client\node_modules\timeago.js\src\utils\date.ts'

WARNING in ./node_modules/timeago.js/esm/utils/dom.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from 'C:\Users\Administrator\Downloads\MERN-Youtube-Clone-main\MERN-Youtube-Clone-main\client\node_modules\timeago.js\src\utils\dom.ts' file: Error: ENOENT: no such file or directory, open 'C:\Users\Administrator\Downloads\MERN-Youtube-Clone-main\MERN-Youtube-Clone-main\client\node_modules\timeago.js\src\utils\dom.ts'

WARNING in src\pages\SignIn.jsx
  Line 74:10:  'email' is assigned a value but never used  no-unused-vars

src\pages\Video.jsx
  Line 10:8:  'Card' is defined but never used  no-unused-vars

src\redux\store.js
  Line 15:10:  'PersistGate' is defined but never used  no-unused-vars

**Comment by shaheen7a** [comment]
Try to remove all node modules an re install it again
rm -rf node_modules
npm install

Or you can try a different version of timeago.js maybe an older version

**Comment by Regis-Loyaute** [comment]
It work with the 3.0.2 timeago.js version, but i these issues:

[eslint]
src\pages\SignIn.jsx
  Line 74:10:  'email' is assigned a value but never used  no-unused-vars

src\pages\Video.jsx
  Line 10:8:  'Card' is defined but never used  no-unused-vars

src\redux\store.js
  Line 15:10:  'PersistGate' is defined but never used  no-unused-vars

Search for the keywords to learn more about each warning.
To ignore, add // eslint-disable-next-line to the line before.

WARNING in [eslint]
src\pages\SignIn.jsx
  Line 74:10:  'email' is assigned a value but never used  no-unused-vars

src\pages\Video.jsx
  Line 10:8:  'Card' is defined but never used  no-unused-vars

src\redux\store.js
  Line 15:10:  'PersistGate' is defined but never used  no-unused-vars

**Comment by shaheen7a** [comment]
You can ignore these warnings if the app works

**Comment by Regis-Loyaute** [comment]
hmmm nothing happens when i click on the sign up button nor the google auth:

![image](https://user-images.githubusercontent.com/84942989/235526696-2cd242da-013a-4ed0-a303-5ef2112836ef.png)
![image](https://user-images.githubusercontent.com/84942989/235526733-0b8f3419-08bf-4d35-957b-21ddf0ff1817.png)
![image](https://user-images.githubusercontent.com/84942989/235526782-720227b6-08d4-4a56-b2d7-0a4fd63f1eae.png)

**Comment by shaheen7a** [comment]
Maybe there is an error with the submit handler check it out
